spring:
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/